name: "Deploy BOT"

on:
  issue_comment:
    types: [created]

jobs:
  rebase-and-push:
    name: Rebase and Push to env

    # If the pull request has been merged
    # if: github.event_name == 'issue_comment' && github.event.pull_request.merged == 'true'

    runs-on: ubuntu-latest


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check User Permission
      uses: actions-cool/check-user-permission@v2.0.1
      with:
        username: ${{ github.actor }}
        require: developer

    - name: Rebase and deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_BRANCH: dev
        SHA_COMMIT: ${{ github.sha }}
        AUTHOR: ${{ github.actor }}
      run: |
        chmod +x ./.github/scripts/rebase-and-deploy-to-env.sh
        ./.github/scripts/rebase-and-deploy-to-env.sh

